/** How each severity, status and rule is labelled and coloured on the alerts page. */

export const SEVERITY_STYLES: Record<string, { badge: string; row: string }> = {
  URGENT:  { badge: "bg-red-800/90 text-red-200 border border-red-600/60",      row: "bg-red-950/30"    },
  ACTION:  { badge: "bg-red-900/80 text-red-300 border border-red-700/50",      row: "bg-red-950/20"    },
  WARNING: { badge: "bg-amber-900/80 text-amber-300 border border-amber-700/50", row: "bg-amber-950/15" },
  INFO:    { badge: "bg-blue-900/80 text-blue-300 border border-blue-700/50",   row: "bg-blue-950/10"   },
};

export const STATUS_STYLES: Record<string, string> = {
  ACTIVE:       "text-amber-400",
  ACKNOWLEDGED: "text-slate-400",
  RESOLVED:     "text-emerald-400",
};

export const RULE_LABELS: Record<string, string> = {
  rrg_transition:      "RRG Transition",
  composite_breakout:  "Composite Breakout",
  composite_breakdown: "Composite Breakdown",
  macro_regime_shift:  "Macro Regime Shift",
  rs_accel_crossover:     "RS Accel Crossover",
  persistence_low:        "Persistence Low",
  breadth_velocity_accel: "Breadth Velocity ↑",
  breadth_velocity_decel: "Breadth Velocity ↓",
  trade_signal_buy:       "BUY Signal",
  trade_signal_reduce:    "REDUCE Signal",
  score_approaching_buy:    "Approaching BUY",
  score_approaching_reduce: "Approaching REDUCE",
  high_conviction_buy:            "High Conviction BUY",
  high_conviction_cluster:        "High Conviction Cluster",
  high_conviction_reduce_cluster: "RISK-OFF Cluster",
  signal_deterioration:           "BUY Momentum Reversal",
  rs_aligned_bull:                "RS Aligned ⊕",
  rs_aligned_bear:                "RS Aligned ⊖",
  rs_breadth_bull:                "RS Breadth ⊕",
  rs_breadth_bear:                "RS Breadth ⊖",
  pre_buy_flow_surge:             "Pre-BUY Flow Surge",
  flow_surge:                     "Flow Surge",
  rrg_rs_divergence:              "RRG/RS Divergence",
  score_percentile_extreme:       "Percentile Extreme",
  score_velocity:                 "Score Velocity",
  multi_alert_bull_confluence:    "Multi-Signal Confluence",
  cross_horizon_rs_divergence:    "Cross-Horizon RS Divergence",
  macro_sector_mismatch:          "Macro/Sector Mismatch",
  sub_sector_breadth_divergence:  "Sub-Sector Breadth Divergence",
  sub_sector_bull_confluence:          "Sub-Sector Bull Confluence",
  theme_dominant_signal_transition:    "Theme Signal",
  theme_momentum_surge:               "Theme Surge",
  theme_momentum_collapse:            "Theme Collapse",
  theme_5d_acceleration:              "Theme 5d Accel",
  theme_distribute_warning:           "Distribution Warning",
  theme_phase_breakout_entry:         "Breakout Entry",
  theme_setup_acceleration:           "Setup Acceleration",
  theme_failed_breakout:              "Failed Breakout",
  theme_phase_fading:                 "Phase Fading",
  theme_momentum_exhaustion:          "Momentum Exhaustion",
  theme_recovery_signal:              "Recovery Signal",
  theme_strong_breakout_confirmation: "Strong Breakout",
  theme_peer_divergence:              "Peer Divergence",
  flow_inflow_5d:         "Flow Inflow (5d)",
  flow_inflow_10d:        "Flow Inflow (10d)",
  flow_inflow_20d:        "Flow Inflow (20d)",
  flow_outflow_5d:        "Flow Outflow (5d)",
  flow_outflow_10d:       "Flow Outflow (10d)",
  flow_outflow_20d:       "Flow Outflow (20d)",
};

export const BUILTIN_RULES = [
  { id: "multi_alert_bull_confluence", label: "Multi-Signal Confluence", condition: "≥3 bullish alerts simultaneously active for one sector", severity: "ACTION", note: "Meta-alert: fires when a single sector has 3 or more bullish signals aligned at the same time — e.g., trade_signal_buy + high_conviction_buy + rs_aligned_bull together. Multiple concurrent signals rarely happen by coincidence; they indicate broad institutional agreement and a high-confidence rotation setup. Resolves when active bullish alert count drops below 3. (Checked last in each evaluation cycle so it captures alerts fired in the same day.)" },
  { id: "cross_horizon_rs_divergence", label: "Cross-Horizon RS Divergence", condition: "RS-20 vs RS-60 direction contradicts RS-60 vs RS-120 direction", severity: "WARNING", note: "Counter-trend / pullback identifier: fires when the short-term RS slope (RS-20 vs RS-60) contradicts the medium-term RS slope (RS-60 vs RS-120). Two patterns: COUNTER_TREND_BOUNCE — RS-20 > RS-60 but RS-60 < RS-120 (short-term strength embedded in a structurally weak sector — fade candidate); PULLBACK_IN_BULL — RS-20 < RS-60 but RS-60 > RS-120 (short-term weakness in a structurally strong sector — potential entry point on the dip). Resolves when both RS slopes agree in direction. Used as an early-turn detector before formal RRG quadrant changes appear." },
  { id: "macro_sector_mismatch", label: "Macro/Sector Mismatch", condition: "Cyclical sector in RRG Leading/Improving during RISK_OFF or STAGFLATION regime", severity: "WARNING", note: "Anomalous rotation alert: fires when a cyclical sector (TECH, DISR, FINL, INDU, ENRG, MATL) shows RRG Leading or Improving momentum while the macro regime is RISK_OFF_FLIGHT or STAGFLATION. This mismatch can signal: (1) the market is early-pricing an economic recovery before macro data confirms it — watch for follow-through; or (2) a false leader that will reverse once risk-off pressure intensifies. Use to tighten stop-losses or scale in cautiously. Resolves when the regime returns to risk-on, or the sector exits quadrant 3/4." },
  { id: "sub_sector_breadth_divergence", label: "Sub-Sector Breadth Divergence", condition: "Parent sector BUY active but <40% of sub-sectors in RRG Leading/Improving", severity: "WARNING", note: "Narrow participation alert: fires when a parent sector has an active BUY trade signal but fewer than 40% of its tracked sub-sectors are in RRG Leading or Improving quadrants. A sector move driven by 1-2 dominant names rather than broad sub-sector participation is more likely to reverse — institutions rotate within sectors before broad moves. Resolves when the parent BUY signal is gone, or when sub-sector breadth recovers above 55%." },
  { id: "sub_sector_bull_confluence", label: "Sub-Sector Bull Confluence", condition: "≥75% of sub-sectors in RRG Leading/Improving", severity: "INFO", note: "Broad participation confirmation: fires when 75%+ of a sector's tracked sub-sectors are simultaneously in Leading or Improving RRG quadrants. This confirms that a sector move has broad internal support — multiple sub-themes are participating, not just one. Pairs with BUY signals to increase conviction; sector breakouts with broad sub-sector participation have historically been more durable. Resolves when sub-sector breadth drops below 55%." },
  { id: "score_velocity", label: "Score Velocity", condition: "5d score change ≥ +12pts (SURGE) or ≤ -12pts (CRASH)", severity: "WARNING", note: "Rate-of-change alert: fires when a sector's composite score moves 12+ percentage points in either direction over 5 trading days. A SURGE (e.g. +14pts in 5d) signals unusual momentum acceleration — the sector is heating up fast regardless of absolute score level. A CRASH signals rapid deterioration — early warning before the formal REDUCE signal. Distinct from score_approaching_buy which tracks absolute score level. Resolves when trend moderates back inside ±5pts." },
  { id: "score_percentile_extreme", label: "Percentile Extreme", condition: "score ≥ 90th or ≤ 10th percentile (252d)", severity: "WARNING", note: "Historical extreme alert: fires when a sector's composite score is at its highest or lowest point in the past 252 trading days. A 90th-percentile HIGH signals potential mean reversion risk (sector may be overextended). A 10th-percentile LOW signals a historically depressed setup — watch for turnaround signals. Resolves when percentile returns to 20th–80th range." },
  { id: "rrg_rs_divergence", label: "RRG/RS Divergence", condition: "RRG quadrant contradicts RS-20 vs RS-60", severity: "WARNING", note: "Early turn signal: fires when a Leading/Improving sector already has RS-20 < RS-60 (momentum cracking before the chart shows it), or when a Lagging/Weakening sector has RS-20 > RS-60 (recovery emerging before the chart catches up). Resolves when the divergence closes." },
  { id: "rs_breadth_bull",   label: "RS Breadth ⊕",       condition: "≥60% of equity sectors have RS-20 > RS-60",  severity: "INFO",    note: "Broad market momentum: when 60%+ of GICS sectors show short-term RS above medium-term RS, it signals institutional rotation is broadly positive — a regime-level tailwind. Resolves below 45%." },
  { id: "rs_breadth_bear",   label: "RS Breadth ⊖",       condition: "≥60% of equity sectors have RS-20 < RS-60",  severity: "WARNING", note: "Broad market deterioration: when 60%+ of GICS sectors show short-term RS below medium-term RS, momentum is broadly deteriorating — market-wide risk-off pressure. Resolves below 45%." },
  { id: "rs_aligned_bull",   label: "RS Aligned ⊕",       condition: "RS-20 > RS-60 > RS-120 (all horizons aligned)", severity: "INFO",    note: "Multi-horizon RS confirmation: short, medium, and long-term RS all in alignment. The strongest RS momentum signal — all three timeframes agree on outperformance." },
  { id: "rs_aligned_bear",   label: "RS Aligned ⊖",       condition: "RS-20 < RS-60 < RS-120 (all horizons aligned)", severity: "WARNING", note: "Multi-horizon RS deterioration: all three RS timeframes confirm sustained underperformance. The most bearish RS configuration — avoid or reduce." },
  { id: "high_conviction_cluster", label: "High Conviction Cluster", condition: "≥3 sectors at conviction ≥75 simultaneously", severity: "ACTION", note: "Broad RISK-ON regime confirmation: when 3+ sectors simultaneously reach multi-factor conviction ≥75. Rarer than individual alerts — indicates a market-wide regime shift, not just one sector." },
  { id: "high_conviction_reduce_cluster", label: "RISK-OFF Cluster", condition: "≥3 sectors at REDUCE conviction ≥40", severity: "ACTION", note: "Broad RISK-OFF regime signal: when 3+ sectors simultaneously reach REDUCE conviction ≥40. Indicates systemic deterioration across the market — consider broad de-risking." },
  { id: "pre_buy_flow_surge", label: "Pre-BUY Flow Surge", condition: "score in [50,65) + flow ≥ +1.5σ",          severity: "WARNING", note: "Institutional positioning signal: score approaching BUY territory AND unusual inflow volume. Institutions often accumulate before price confirms — this leads the formal BUY by 1-3 days." },
  { id: "high_conviction_buy",    label: "High Conviction BUY",   condition: "conviction score ≥ 75",           severity: "ACTION",  note: "Multi-factor conviction ≥75: signal quality + macro fit + 252d percentile + momentum acceleration — the highest-quality BUY signals only" },
  { id: "trade_signal_buy",       label: "BUY Signal",            condition: "score ≥ 65, RRG 3/4, trend > 0",  severity: "ACTION",  note: "Full BUY signal: all 3 conditions align for the first time — most actionable alert" },
  { id: "score_approaching_buy",  label: "Approaching BUY",       condition: "score enters [55, 65)",           severity: "INFO",    note: "Early warning 1-5 days before a full BUY signal — prepare position" },
  { id: "trade_signal_reduce",      label: "REDUCE Signal",         condition: "score < 35, RRG 1/2",              severity: "WARNING", note: "REDUCE signal: score and RRG both deteriorating — consider trimming" },
  { id: "score_approaching_reduce", label: "Approaching REDUCE",    condition: "score drops into (35, 45]",        severity: "WARNING", note: "Early warning before full REDUCE — score entering deterioration zone" },
  { id: "signal_deterioration",     label: "BUY Momentum Reversal", condition: "score ≥ 65 but 5d trend < -5pts",  severity: "WARNING", note: "BUY position at risk: composite score still in BUY territory but declining sharply in 5 days. Monitor for signal exit — precedes a formal REDUCE alert by 3–7 days on average." },
  { id: "rrg_transition",         label: "RRG Transition",        condition: "RRG quadrant changes",            severity: "INFO",    note: "Category enters any new RRG quadrant (Leading/Improving/Weakening/Lagging)" },
  { id: "composite_breakout",     label: "Composite Breakout",    condition: "composite_score > 0.70",          severity: "ACTION",  note: "Score crosses above 0.70 — entering strong signal territory" },
  { id: "composite_breakdown",    label: "Composite Breakdown",   condition: "composite_score < 0.35",          severity: "WARNING", note: "Score falls below 0.35 — REDUCE threshold crossed" },
  { id: "macro_regime_shift",     label: "Macro Regime Shift",    condition: "regime changes",                  severity: "WARNING", note: "Macro regime changes on new data — re-evaluate macro-fit scores" },
  { id: "rs_accel_crossover",     label: "RS Accel Crossover",    condition: "rs_60 crosses rs_120",            severity: "INFO",    note: "Near-term RS crosses long-term baseline — momentum inflection" },
  { id: "breadth_velocity_accel", label: "Breadth Velocity ↑",   condition: "5d rate sharply above 15d rate", severity: "INFO",    note: "Hit-rate accelerating: sector outperforming benchmark at an increasing rate over recent 5 days" },
  { id: "breadth_velocity_decel", label: "Breadth Velocity ↓",   condition: "5d rate sharply below 15d rate", severity: "WARNING", note: "Hit-rate decelerating: sector outperformance fading vs recent baseline" },
  { id: "persistence_low",        label: "Persistence Low",       condition: "persistence_20d < threshold",     severity: "WARNING", note: "Sector beats its benchmark on fewer than 7 of the last 20 trading days" },
  { id: "flow_inflow_20d",        label: "Flow Inflow (20d)",     condition: "flow_20d > threshold",            severity: "INFO",    note: "Sustained 20-day inflow above baseline (not yet implemented — ETF flow data pending)" },
  { id: "flow_outflow_20d",       label: "Flow Outflow (20d)",    condition: "flow_20d < threshold",            severity: "WARNING", note: "Sustained 20-day outflow below baseline (not yet implemented — ETF flow data pending)" },
  { id: "theme_momentum_surge",    label: "Theme Surge",           condition: "avg 20d trend > +0.01 across theme constituents", severity: "ACTION",  note: "Theme acceleration alert: fires when the average 20-day composite trend velocity across a theme's ETF constituents exceeds +0.010 (≈ +1pt/day). This indicates rapid momentum acceleration within a theme — the ETFs that define the theme are collectively gaining score faster than the background market. Fires before the formal BUY signal transition (which requires ≥50% of constituents above 0.65) — a 1-3 day early warning. Resolves when avg trend drops below +0.003." },
  { id: "theme_momentum_collapse", label: "Theme Collapse",        condition: "avg 20d trend < -0.01 across theme constituents", severity: "WARNING", note: "Theme deceleration alert: fires when the average 20-day composite trend velocity across a theme's ETF constituents drops below -0.010. This signals rapid momentum collapse — the theme's ETFs are collectively losing score faster than background. Early warning to reduce exposure before the formal REDUCE signal. Resolves when avg trend recovers above -0.003." },
  { id: "theme_5d_acceleration",       label: "Theme 5d Accel",       condition: "5d trend exceeds 20d trend by ≥0.008/day",         severity: "ACTION",  note: "Momentum regime-change signal: fires when a theme's average 5-day trend velocity outpaces its 20-day trend by ≥0.008/day (≈ +0.8pt/day delta). Short-term momentum is accelerating faster than the established baseline — a momentum regime shift in progress. Typically leads breakout entries by 1-3 days. Resolves when the 5d-vs-20d gap narrows below 0.003." },
  { id: "theme_distribute_warning",    label: "Distribution Warning", condition: "score ≥ 0.65 but avg 20d flow < -0.5",             severity: "WARNING", note: "Smart money exit signal: fires when a theme composite score is in BUY territory (≥0.65) but the average 20-day flow z-score across constituents drops below -0.5σ. Price strength with deteriorating flow is a classic distribution pattern — institutions exiting into retail strength. Early warning to tighten stops on existing positions. Resolves when flow recovers above 0." },
  { id: "theme_phase_breakout_entry",  label: "Breakout Entry",       condition: "theme enters BREAKOUT phase (was lower 5d ago)",   severity: "ACTION",  note: "Phase transition alert: fires when a theme transitions into the BREAKOUT phase (score ≥ 0.65, 5d trend > 0, 20d trend > 0) from a non-BREAKOUT phase 5 trading days ago. Confirms genuine phase advancement — not a brief score spike. The cleanest institutional entry signal in the theme lifecycle. Resolves when the theme exits BREAKOUT (score drops below 0.62 or trends turn negative)." },
  { id: "theme_setup_acceleration",    label: "Setup Acceleration",   condition: "SETUP phase (0.52–0.65) + 5d trend ≥ 0.008/day",  severity: "ACTION",  note: "Pre-breakout warning: fires when a theme is in the SETUP phase (avg score 0.52–0.65) and the 5-day trend accelerates above 0.008/day. This combination — near-breakout score level + accelerating short-term momentum — is the earliest reliable precursor to a BREAKOUT phase entry. Fires 1-5 days before the formal BREAKOUT. Resolves when score exceeds the SETUP ceiling (0.65) or drops below 0.48." },
  { id: "theme_failed_breakout",       label: "Failed Breakout",      condition: "score drops from ≥0.65 to <0.57 within 5 days",   severity: "WARNING", note: "Breakout failure signal: fires when a theme's composite score drops from BUY zone (≥0.65) to below 0.57 within 5 trading days. A failed breakout is one of the most reliable reversal patterns — price appeared to cross the key threshold but couldn't sustain it. Consider full exit rather than waiting for a REDUCE signal. Resolves when score recovers above 0.62." },
  { id: "theme_phase_fading",          label: "Phase Fading",         condition: "theme enters FADING phase (was higher-phase 5d ago)", severity: "WARNING", note: "Phase degradation alert: fires when a theme transitions into the FADING phase (score declining, 5d trend < -0.003, 20d trend negative) from a higher phase 5 trading days ago. Confirms genuine phase deterioration rather than a one-day dip. Suggests reducing or exiting positions — the theme's internal momentum is structurally breaking down. Resolves when score recovers above 0.55 or 5d trend turns positive." },
  { id: "theme_momentum_exhaustion",   label: "Momentum Exhaustion",  condition: "score ≥ 0.65 + 5d trend < -0.005 + 20d trend < 0", severity: "WARNING", note: "Early exit signal: fires when a BUY-zone theme (composite score ≥ 0.65) shows negative 5-day AND 20-day composite trend simultaneously. Score hasn't broken down yet but both momentum windows are already deteriorating — an early warning before the score actually drops. Similar to distribution warning but based on internal momentum rather than flow. Resolves when score drops below 0.60 (risk managed) or 5d trend recovers above +0.002." },
  { id: "theme_recovery_signal",       label: "Recovery Signal",      condition: "score 35–55, 5d trend > 0, 20d trend was negative 5d ago", severity: "INFO", note: "Early recovery detector: fires when a FADING or WEAK theme shows nascent recovery — composite score in the 35–55 range, 5-day trend turning positive (>0.003/day), while the 20-day trend was still negative 5 trading days ago. Captures the first measurable positive momentum after a downtrend, before a full phase upgrade. Watch for follow-through: if score advances above 0.60, the recovery is confirmed; below 0.30, the downtrend resumed. Resolves when score rises above 0.60 (confirmed recovery) or falls below 0.30 (failed)." },
  { id: "theme_strong_breakout_confirmation", label: "Strong Breakout", condition: "score ≥ 0.70 AND prior-20d score < 0.65",               severity: "ACTION", note: "Follow-through confirmation: fires when a theme's composite score reaches ≥0.70 (well into BUY territory) while it was below 0.65 (outside BUY zone) 20 trading days ago. This is not just a breakout — it's a breakout with institutional follow-through. A theme that reaches 70 from below 65 in 20 days has demonstrated sustained momentum, not just a spike. Most reliable when paired with an active Breakout Entry or Theme 5d Accel alert. Resolves when score drops back below 0.65." },
  { id: "theme_peer_divergence",             label: "Peer Divergence", condition: "≥3 constituents, max−min spread >30 pts, avg >0.40",         severity: "INFO",   note: "Internal rotation detector: fires when a theme's constituent composite scores diverge by more than 30 percentage points — one sub-sector leading (high score) while another lags (low score) — AND the theme average is above 0.40 (theme still active). This spread signals within-theme rotation: institutions may be repositioning from the laggard into the leader or waiting for the laggard to catch up. The leader/laggard identifiers and spread size appear in the alert message. Resolves when the spread falls below 20 pts (constituents re-converge)." },
];

/** The colour of a severity chip, and the tint its row gets. */
export const severityBadgeClass = (severity: string): string =>
  SEVERITY_STYLES[severity]?.badge ?? "bg-slate-700 text-slate-300 border border-slate-600";

export const severityRowClass = (severity: string): string => SEVERITY_STYLES[severity]?.row ?? "";
